language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install: poetry install
script: make test

after_success:
  # Send coverage to coveralls:
  - pip install coveralls
  - coveralls
  # Send coverage to deepsource:
  - curl https://deepsource.io/cli | sh
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml

notifications:
  email:
    on_success: never
    on_failure: change
