# `wemake` style file for nitpick
# https://raw.githubusercontent.com/andreoliwa/nitpick/v0.18.0/nitpick-style.toml

[nitpick]
minimum_version = "0.21.0"

[nitpick.styles]
include = [
  "file-structure.toml",
  "flake8.toml",
  "isort.toml",
  "mypy.toml",
  "poetry.toml",
  "styleguide.toml"
]
